# Lab 4

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/giswqs/geog-510/blob/main/book/labs/lab_04.ipynb)

## Exercise 1: Variable Assignment and Basic Operations

Create variables to store the following geospatial data:

- The latitude and longitude of New York City: 40.7128, -74.0060.
- The population of New York City: 8,336,817.
- The area of New York City in square kilometers: 783.8.

Perform the following tasks:

1. Calculate and print the population density of New York City (population per square kilometer).
2. Print the coordinates in the format "Latitude: [latitude], Longitude: [longitude]".

In [1]:
nyc = {
    "latitude": 40.7128,
    "longitude": -74.0060,
    "population": 8336817,
    "area": 783.8,
}
 


In [2]:
#Pop density
pop_desnisty = (nyc["population"] / nyc["area"])
print(pop_desnisty)

10636.408522582293


In [3]:
 #print lat & lon
print(f"Latitude: {nyc["latitude"]}, Longitude: {nyc["longitude"]}")


Latitude: 40.7128, Longitude: -74.006


## Exercise 2: Working with Strings

Create a string variable to store the name of a city, such as "San Francisco". Perform the following operations:

1. Convert the string to lowercase and print the result.
2. Convert the string to uppercase and print the result.
3. Replace "San" with "Los" in the city name and print the new string.

In [4]:
city = "San Fransisco"

# Question 1
city_lowercase = city.lower()
print(city_lowercase)

# Question 2
city_uppercase = city.upper()
print(city_uppercase)

# Question 3
city_new = city.replace("San", "Los")
# method 2 city_prefix = "Los" + city[3:]
print(city_new)


san fransisco
SAN FRANSISCO
Los Fransisco


## Exercise 3: Using Lists

Create a list of tuples, where each tuple contains the name of a city and its corresponding latitude and longitude:

- New York City: (40.7128, -74.0060)
- Los Angeles: (34.0522, -118.2437)
- Chicago: (41.8781, -87.6298)

Perform the following tasks:

1. Add a new city (e.g., Miami: (25.7617, -80.1918)) to the list.
2. Print the entire list of cities.
3. Slice the list to print only the first two cities.

In [33]:
# List of cities with coordinates
cities = [
    ("New York City", (40.7128, -74.0060)),
    ("Los Angeles", (34.0522, -118.2437)),
    ("Chicago", (41.8781, -87.6298))
        ]

# Question 1
cities.append(("Miami", (25.7617, -80.1918)))
# Question 2
print(cities)

# Question 3
print(cities[0:2])

[('New York City', (40.7128, -74.006)), ('Los Angeles', (34.0522, -118.2437)), ('Chicago', (41.8781, -87.6298)), ('Miami', (25.7617, -80.1918))]
[('New York City', (40.7128, -74.006)), ('Los Angeles', (34.0522, -118.2437))]


## Exercise 4: Using Tuples

Create a tuple to store the coordinates (latitude, longitude) of the Eiffel Tower: (48.8584, 2.2945). Perform the following tasks:

1. Access and print the latitude and longitude values from the tuple.
2. Try to change the latitude value to 48.8585. What happens? Explain why.

In [ ]:
eiffel_tower = (48.8584, 2.2945)

# Question 1
print("latitude:", eiffel_tower[0])
print("longitude:", eiffel_tower[1])

# Question 2
# eiffel_tower[0] = 41.6619
# This results in an error message ('tuple' object does not support item assignment).
# This is because tuples are immutable, meaning they cannot be changed once created.


latutude: 48.8584
longitude: 2.2945


## Exercise 5: Working with Sets

Create a set of countries you have visited, such as {"USA", "France", "Germany"}. Perform the following tasks:

1. Add a new country to the set.
2. Try to add the same country again. What happens?
3. Print the updated set.

In [35]:
visited_countries = {"France", "Zambia", "United States", "Kenya"}

# Question 1
visited_countries.add("Italy")


# Question 2 & 3
# Nothing happens when you try to add an element that already exists in the set. No duplicates are allowed.
visited_countries.add("Italy")
print(visited_countries)




{'Italy', 'Zambia', 'France', 'Kenya', 'United States'}


## Exercise 6: Working with Dictionaries

Create a dictionary to store information about a specific geospatial feature, such as a river:

- Name: "Amazon River"
- Length: 6400 km
- Countries: ["Brazil", "Peru", "Colombia"]

Perform the following tasks:

1. Add a new key-value pair to the dictionary to store the river's average discharge (e.g., 209,000 m³/s).
2. Update the length of the river to 6992 km.
3. Print the dictionary.

In [36]:
river = {"Name": "Amazon River",
         "Length": "6400 km",
         "Countries": ["Brazil", "Peru", "Colombia"]
        }

# Question 1
river["discharge"] = "209,000 m³/s"

#Question 2
river["Length"] = "6992 km"

#Question 3
print(river)

{'Name': 'Amazon River', 'Length': '6992 km', 'Countries': ['Brazil', 'Peru', 'Colombia'], 'discharge': '209,000 m³/s'}


## Exercise 7: Nested Data Structures

Create a dictionary to represent a city that contains the city's name, population, and coordinates (latitude, longitude):

- Name: "Tokyo"
- Population: 13,515,271
- Coordinates: (35.6895, 139.6917)

Perform the following tasks:

1. Access and print the population of the city.
2. Access and print the city's latitude.
3. Update the population to 14,000,000 and print the updated dictionary.

In [37]:
city_name = {
            "Name": "Tokyo",
            "Population": 13515271,
            "Coordinates": (35.6895, 139.6917)
            }

# Question 1
print(city_name["Population"])

# Question 2
print(city_name["Coordinates"][0])

# Question 3
city_name["Population"]= 14000000
print(city_name)


13515271
35.6895
{'Name': 'Tokyo', 'Population': 14000000, 'Coordinates': (35.6895, 139.6917)}


## Exercise 8: List Operations

Given the list of cities from Exercise 3, perform the following operations:

1. Sort the list of cities alphabetically by name.
2. Create a new list that contains only the city names.
3. Remove the last city from the original list and print the updated list.

In [39]:
# List of cities with coordinates
cities = [
    ("New York City", (40.7128, -74.0060)),
    ("Los Angeles", (34.0522, -118.2437)),
    ("Chicago", (41.8781, -87.6298))
        ]

# Question 1
cities.sort()
print(cities)

# Question 2
# first convert the list to dictionary
cities_dic = dict(cities)
#print(cities_dic.keys())
# Create a new list with only city names
city_names = [city[0] for city in cities]
print(city_names)

# Question 3
cities.pop()
print(cities)

[('Chicago', (41.8781, -87.6298)), ('Los Angeles', (34.0522, -118.2437)), ('New York City', (40.7128, -74.006))]
['Chicago', 'Los Angeles', 'New York City']
[('Chicago', (41.8781, -87.6298)), ('Los Angeles', (34.0522, -118.2437))]


## Exercise 9: Dictionary Operations

Using the dictionary from Exercise 6, perform the following tasks:

1. Check if the key "Length" exists in the dictionary.
2. Print all the keys in the dictionary.
3. Print all the values in the dictionary.

In [40]:
river = {"Name": "Amazon River",
         "Length": "6400 km",
         "Countries": ["Brazil", "Peru", "Colombia"]
        }

# Question 1
if "Length" in river:
    print("The key length exists in the dictionary.")

# Question 2
print(river.keys())

# Question 3
print(river.values())

The key length exists in the dictionary.
dict_keys(['Name', 'Length', 'Countries'])
dict_values(['Amazon River', '6400 km', ['Brazil', 'Peru', 'Colombia']])


## Exercise 10: Practical Application

Imagine you have a list of tuples, each representing a location with its name, latitude, and longitude:

In [31]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]

Perform the following tasks:

1. Create a new list that contains only the names of the locations.
2. Create a dictionary where the keys are location names and the values are tuples of their coordinates.
3. Print the latitude of "K2" using the dictionary.

In [ ]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475)
]
# Question 1
name_location = [loca[0] for loca in locations]
print(name_location)

# Question 2
# this is coz the list is a list of tuples have no 2 ltems to ley and val instead its three values
dic_locations = {loca[0]: (loca[1], loca[2]) for loca in locations}
print(dic_locations)

# Question 3
print(f"location of latitude K2 is : {dic_locations["K2"][0]}")

['Mount Everest', 'K2', 'Kangchenjunga']
{'Mount Everest': (27.9881, 86.925), 'K2': (35.8808, 76.5155), 'Kangchenjunga': (27.7025, 88.1475)}
location of latitude K2 is: 35.8808


## Exercise 11: Manipulating Geographic Location Strings

- Create a string that represents the name of a geographic feature (e.g., `"Amazon River"`).
- Convert the string to lowercase and then to uppercase.
- Concatenate the string with the name of the country (e.g., `"Brazil"`) to create a full location name.
- Repeat the string three times, separating each repetition with a dash (`-`).

In [29]:
river_name = "Amazon River"
river_name_lowercase = river_name.lower()
print(river_name_lowercase)

river_name_uppercase = river_name.upper()
print(river_name_uppercase)

river_name_full = river_name + " Brazil"

river_3x = (river_name_full + " - ") * 3
river_3x = river_3x.rstrip(" - ")  # Remove the trailing hyphen and space
print(river_3x)


amazon river
AMAZON RIVER
Amazon River Brazil - Amazon River Brazil - Amazon River Brazil


## Exercise 12: Extracting and Formatting Coordinates

- Given a string with the format `"latitude, longitude"` (e.g., `"40.7128N, 74.0060W"`), extract the numeric values of latitude and longitude.
- Convert these values to floats and remove the directional indicators (`N`, `S`, `E`, `W`).
- Format the coordinates into a `POINT` WKT string (e.g., `"POINT(-74.0060 40.7128)"`).

In [26]:
latitude, longitude = "40.7128N", "74.0060W"
latitude = float(latitude[:-1])
longitude = float(longitude[:-1])   
print(latitude, longitude)

wkt_format = f"POINT({longitude} {latitude})"
print(wkt_format)


40.7128 74.006
POINT(74.006 40.7128)


## Exercise 13: Building Dynamic SQL Queries

- Given a table name and a condition, dynamically build an SQL query string.
- Example: If `table_name = "cities"` and `condition = "population > 1000000"`, the query should be `"SELECT * FROM cities WHERE population > 1000000;"`.
- Add additional conditions dynamically, like `AND` clauses.

In [25]:
table_name = "cities"
population = 1000000

sql_text = f"SELECT * FROM {table_name} WHERE population > {population}"
print(sql_text)


SELECT * FROM cities WHERE population > 1000000


## Exercise 14: String Normalization and Cleaning

- Given a list of city names with inconsistent formatting (e.g., `[" new york ", "Los ANGELES", "   CHICAGO"]`), normalize the names by:
  - Stripping any leading or trailing whitespace.
  - Converting them to title case (e.g., `"New York"`, `"Los Angeles"`, `"Chicago"`).
- Ensure that the output is a clean list of city names.

In [24]:
city_name_list = [" new york ", "Los ANGELES", "   CHICAGO"]
# Strip white space & title case
city_name_list_clean = [city.strip().title() for city in city_name_list]
print(city_name_list_clean)



['New York', 'Los Angeles', 'Chicago']


## Exercise 15: Parsing and Extracting Address Information

- Given a string in the format `"Street, City, Country"` (e.g., `"123 Main St, Springfield, USA"`), write a function that parses the string into a dictionary with keys `street`, `city`, and `country`.
- The function should return a dictionary like `{"street": "123 Main St", "city": "Springfield", "country": "USA"}`.

In [23]:
string_1 = "Street, City, Country"
string_2 = "123 Main St, Springfield, USA"
list_1 = string_1.split(", ")
list_2 = string_2.split(", ")

# convert the list to dictionary

string_dict= dict(zip(list_1, list_2))
print(string_dict)



{'Street': '123 Main St', 'City': 'Springfield', 'Country': 'USA'}


## Exercise 16: Using For Loops to Process Coordinate Lists

- Create a list of tuples representing coordinates (latitude, longitude).
- Write a `for` loop that prints each coordinate and indicates whether it is in the Northern or Southern Hemisphere based on the latitude.

In [22]:
coord_list = [(-23.7128, 27.0060), (34.0522, -118.2437), (41.8781, -87.6298), (-12.089, 32.453)]

for coord in coord_list:
    lat, lon = coord
    #print(f"Latitude: {lat}, Longitude: {lon}")
    if lat > 0:
     print(f"Coordinate {coord} is in the Northern Hemisphere")
    elif lat < 0:
        print(f"Coordinate {coord} is in the Southern Hemisphere")
    else:  
        print(f"Coordinate {coord} is on the Equator")


Coordinate (-23.7128, 27.006) is in the Southern Hemisphere
Coordinate (34.0522, -118.2437) is in the Northern Hemisphere
Coordinate (41.8781, -87.6298) is in the Northern Hemisphere
Coordinate (-12.089, 32.453) is in the Southern Hemisphere


## Exercise 17: While Loops for Iterative Processing

- Create a list of coordinates (latitude, longitude).
- Write a `while` loop that continues to print each coordinate until it encounters a coordinate with a negative latitude.
- Stop the loop once this condition is met.

In [21]:
coord_list = [(45.4093,96.9837),(43.7128, -27.0060),(-12.089, 32.453), (34.0522, -118.2437), (41.8781, -87.6298)]
len(coord_list)

num = 0
while num < len(coord_list): 
    lat, lon = coord_list[num]
    if lat > 0:
        print(f"latitude: {lat}, Longitude: {lon}")
    else:
        print("Negative latitude, breaking the loop.")
        break
    num += 1


latitude: 45.4093, Longitude: 96.9837
latitude: 43.7128, Longitude: -27.006
Negative latitude, breaking the loop.


## Exercise 18: Conditional Logic in Loops

- Create a list of coordinates and use a `for` loop to iterate over them.
- Use an `if-elif-else` statement inside the loop to classify each coordinate based on its longitude:
  - Print `"Eastern Hemisphere"` if the longitude is greater than 0.
  - Print `"Western Hemisphere"` if the longitude is less than 0.

In [20]:
coordinates = [(45.4093,96.9837),(43.7128, -27.0060),(-12.089, 32.453), (34.0522, -118.2437), (41.8781, -87.6298)]

for coord in coordinates:
    lat, lon = coord    
    #print(f"Latitude: {lat}, Longitude: {lon}")
    if lon>0:
        print(f"Coordinate {coord} is in the Eastern Hemisphere")
    elif lon<0:
        print(f"Coordinate {coord} is in the Western Hemisphere")
    elif lon==0:
        print(f"Coordinate {coord} is on the Prime Meridian")



Coordinate (45.4093, 96.9837) is in the Eastern Hemisphere
Coordinate (43.7128, -27.006) is in the Western Hemisphere
Coordinate (-12.089, 32.453) is in the Eastern Hemisphere
Coordinate (34.0522, -118.2437) is in the Western Hemisphere
Coordinate (41.8781, -87.6298) is in the Western Hemisphere


## Exercise 19: Filtering Data with Combined Loops and Conditionals

- Given a list of coordinates, filter out and store only those located in the Southern Hemisphere (latitude < 0).
- Count the number of coordinates that meet this condition and print the result.

In [19]:
coordinates_list = [(45.4093,96.9837),(43.7128, -27.0060),(-12.089, 32.453), (34.0522, -118.2437), (-31.8781, -87.6298)]
southern_hemisphere = []
for co in coordinates_list:
    lat, lon = co
    if lat < 0:
        southern_hemisphere.append(co)
print(southern_hemisphere)

# Number of filtered coordinates
print(f"\nNumber of coordinates meeting the condition is {len(southern_hemisphere)}")


[(-12.089, 32.453), (-31.8781, -87.6298)]

Number of coordinates meeting the condition is 2


## Exercise 20: Generating and Analyzing Random Coordinates

- Write a program that generates random coordinates (latitude between [-90, 90] degrees and longitude between [-180, 180] degrees).
- Use a `while` loop to keep generating coordinates until a pair with both latitude and longitude greater than 50 is generated.
- Print each generated coordinate and the final coordinate that meets the condition.

In [13]:
import random
def generate_random_coords():
    while True:
        latitude = random.uniform(-90, 90)
        longitude = random.uniform(-180, 180)
        
        print(f"Generated coordinates: Latitude = {latitude:.4f}, Longitude = {longitude:.4f}")
        
        if latitude > 50 and longitude > 50:
            print("\nFinal coordinates with lat & lon >50:")
            print(f"Latitude = {latitude:.4f}, Longitude = {longitude:.4f}")
            break


generate_random_coords()

Generated coordinates: Latitude = 39.6462, Longitude = -152.9551
Generated coordinates: Latitude = -8.8785, Longitude = -99.1567
Generated coordinates: Latitude = 46.5948, Longitude = 41.1067
Generated coordinates: Latitude = -53.6432, Longitude = -11.8498
Generated coordinates: Latitude = -35.9400, Longitude = 90.8558
Generated coordinates: Latitude = -49.4047, Longitude = -12.7015
Generated coordinates: Latitude = -64.5574, Longitude = -89.2726
Generated coordinates: Latitude = -7.0180, Longitude = -61.8425
Generated coordinates: Latitude = 72.2100, Longitude = -27.2079
Generated coordinates: Latitude = -69.7473, Longitude = -157.0732
Generated coordinates: Latitude = 16.8129, Longitude = 44.5104
Generated coordinates: Latitude = -51.1449, Longitude = -2.6248
Generated coordinates: Latitude = -12.6915, Longitude = -130.1501
Generated coordinates: Latitude = -26.0453, Longitude = -55.9852
Generated coordinates: Latitude = 24.4190, Longitude = 123.2280
Generated coordinates: Latitude =

## Submission Requirements

Complete the exercises above and and upload the notebook to your GitHub repository. Make sure the notebook has a Colab badge at the top so that it can be easily opened in Google Colab. Submit the URL of the notebook to Canvas.